name: Github Action Demo
on: push
jobs:
  Premier-job:
    name: premierJob
    runs-on: ubuntu-latest
    steps:
      - run: echo "premier job"
      - run: echo "fin du job"
  Second-job:
    name: secondJob
    runs-on: ubuntu-latest
    steps:
      - run: echo "deuxieme job"
      - run: echo "fin du job"
